---
- hosts: all
  tasks:

  - name: "Creating jails directory"
    file:
      path: /opt/maics_jails/
      state: directory
      mode: 0755

  - name: check if jail exists
    stat:
        path: "/opt/maics_jails/{{shell_name}}"
    register: shell_stat

  - name: seeking default shell
    shell: which "{{default_shell}}"
    register: shell_location
    when: not shell_stat.stat.exists

  - name: creating jail
    shell: "cp {{shell_location.stdout}} /opt/maics_jails/{{shell_name}}"
    when: not shell_stat.stat.exists

  - name: uploading restricted shell profile
    template:
      src: ../templates/confinement-shells-deploy/shell.prof.template
      dest: "/etc/apparmor.d/opt.maics_jails.{{shell_name}}"

  - name: set shell mode mode
    shell: "aa-{{shell_mode}} /etc/apparmor.d/opt.maics_jails.{{shell_name}}"

  - name: reload profile
    shell: "apparmor_parser -r /etc/apparmor.d/opt.maics_jails.{{shell_name}}"
