

---
- hosts: all
  tasks:
  - name: check for skdc client installed
    stat:
      path: /usr/sbin/maics-ward
    register: deployed

  - name:
    fail:
      msg: "maics-ward-undeployed : maics client not deployed, click to deploy"
    when: not deployed.stat.exists
