---
- hosts: all
  gather_facts: no
  tasks:
  - name: check for MAICS client installed
    stat:
      path: /usr/sbin/maics-ward
    register: deployed

  - name:
    fail:
      msg: "maics-ward-undeployed : maics client not deployed, click to deploy"
    when: not deployed.stat.exists

  - name: registering ecdsa key
    shell: cat /etc/ssh/ssh_host_ecdsa_key.pub
