###############################################################################
#
# Deploy client
#
###############################################################################

---
- hosts: all
  tasks:

  - name: Update repositories cache and install golang and git packages
    apt:
        name:
        - git
        - golang
        update_cache: yes

  - name: retriveing root public key for maics
    shell: "cat /home/{{maics_user}}/.ssh/id_rsa.pub"
    delegate_to: localhost
    register: id_rsa_pub

  - name: "copying source file..."
    template:
      src: ../templates/maics-ward-deploy/maics-ward.go
      dest: /tmp/maics-ward.go

  - name: "Installing required packcages"
    shell: go get github.com/lucabodd/go-ldap-client

  - name: "building sources"
    shell: go build -o /usr/sbin/maics-ward /tmp/maics-ward.go

  - name: "removing golang sources"
    file:
      path: /tmp/maics-ward.go
      state: absent
