###############################################################################
#
# Deploy client
#
###############################################################################

---
- hosts: all
  gather_facts: no
  tasks:

  - name: Update repositories cache and install golang and git packages
    apt:
        name:
        - git
        update_cache: yes

  - name: unarchive go to /usr/local/
    unarchive:
      src: https://dl.google.com/go/go1.15.5.linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes

  - name: Edit /etc/profile
    lineinfile:
      path: /etc/profile
      line: 'export PATH=$PATH:/usr/local/go/bin'
      state: present

  - name: installing required golang libs
    shell: /usr/local/go/bin/go get -u github.com/tidwall/gjson

  - name: "Installing required packcages"
    shell: /usr/local/go/bin/go get -u github.com/lucabodd/go-ldap-client

  # Installing maics-wards
  - name: retriveing root public key for maics
    shell: "cat /home/{{maics_user}}/.ssh/id_rsa.pub"
    delegate_to: localhost
    register: id_rsa_pub

  - name: "copying source file..."
    template:
      src: ../templates/maics-ward-deploy/maics-ward.go
      dest: /tmp/maics-ward.go

  - name: "building sources"
    shell: /usr/local/go/bin/go build -o /usr/sbin/maics-ward /tmp/maics-ward.go

  - name: "removing golang sources"
    file:
      path: /tmp/maics-ward.go
      state: absent

  # Installing maics-rku
  - name: templating ecdsa private key
    shell: cat /etc/ssh/ssh_host_ecdsa_key
    register: ecdsa_private_key

  - name: "copying source file..."
    template:
      src: ../templates/maics-rku-deploy/maics-rku.go
      dest: /tmp/maics-rku.go

  - name: "copying pkg libs..."
    copy:
        src: ../templates/maics-rku-deploy/pkg
        dest: /tmp/

  - name: "building sources"
    shell: /usr/local/go/bin/go build -o /usr/bin/maics-rku /tmp/maics-rku.go

  - name: "removing golang sources"
    file:
      path: /tmp/maics-rku.go
      state: absent

  - name: "removing golang pkg sources"
    file:
      path: /tmp/pkg
      state: absent
