###############################################################################
#
# Deploy ssh key
#
###############################################################################

---
- hosts: all
  become: "{{ 'yes' if sudo is defined or su is defined else 'no' }}"
  become_method: "{{ 'sudo' if sudo is defined else 'su' }}"

  tasks:
  - name: Set authorized key
    authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
